### ISSUE TITLE
 `HTTP error 400.` error when trying to export pdf.   

### ISSUE THREAD

**Issue by theoryshaw** [benweet/stackedit#1822] opened 2023-05-24 16:32 UTC
get the following error when trying to export pdf. 

Currently a sponsor. 

`HTTP error 400.`

**Comment by benweet** [comment] 2023-05-25 07:38
I can reproduce that with documents containing horizontal rules :

```
---
```

The problem is described here : https://github.com/jgm/pandoc/issues/5801
Not sure how to fix it yet but it should work if you remove the horizontal rules from your document.

**Comment by benweet** [comment] 2023-05-27 13:24
Should be fixed with v5.15.2.

**Closed by benweet** 2023-05-27 13:24 UTC
