### ISSUE TITLE
Rendering messed up when changing settings on Google Chrome

### ISSUE THREAD

**Issue by bloff** [benweet/stackedit#706] opened 2015-02-23 14:36 UTC
I just changed the Settings>Extensions>Markdown Extra>Syntax highlighter setting to "None", as suggested by a previous issue (https://github.com/benweet/stackedit/issues/703#issuecomment-75435022), but the editor fails to render properly after this (in the lastest google chrome for linux).

This has happened to me before when trying to change other settings. 

With firefox it seems to work just fine.

![screenshot from 2015-02-23 15 30 01](https://cloud.githubusercontent.com/assets/3836039/6329488/125113e4-bb71-11e4-98b9-ddf49f11f192.png)

**Comment by benweet** [comment] 2015-02-23 14:43
It may be a compatibility issue with your chrome plugins. Can you try with an incognito window?

**Comment by bloff** [comment] 2015-02-23 16:04
Disabling all extensions, changing the setting and then reenabling allowed it to work. Would you like me to try and figure out precisely which extension was interfeering?

**Comment by benweet** [comment] 2015-02-23 16:23
If you have time, that would help other users facing this issue. But the problem is not in the application itself, so I'll close this one.

**Closed by benweet** 2015-02-23 16:23 UTC
