### ISSUE TITLE
MathJax/Latex not rendering with single $

### ISSUE THREAD

**Issue by IanJermyn** [benweet/stackedit#923] opened 2015-12-15 12:42 UTC
The rendering of Mathjax/Latex expressions with single $ delimiters appears to be broken. Double $$ delimiters seem fine.

**Comment by pkra** [comment] 2015-12-15 15:56
Works fine for me in a clean environment. Have you disabled the setting? (Settings => "LaTeX mathematical expressions using $ and $$ delimiters")

**Comment by IanJermyn** [comment] 2015-12-15 17:44
No - I checked this setting. The same markdown works in Classeur, so it is
hard to believe it is something in my environment. Should I try 'Reset
application' or 'StackEdit recovery'?

**Comment by IanJermyn** [comment] 2016-03-04 08:52
The issue persists in the new version. I repeat that there is no problem in Classeur Beta: both inline and display equations work. This suggests to me that the problem is with StackEdit, not with my settings or environment. I sponsor StackEdit, so I would appreciate a reply, please.

**Comment by benweet** [comment] 2016-03-04 09:53
Works fine to me. Have you tried to reset your settings? (Settings>Utils>Load default settings)

**Comment by pkra** [comment] 2016-03-04 10:36
It might also help to post a sample. E.g., if you mix HTML elements into the TeX string (by accident, from copy&paste etc), then MathJax will stop parsing the expression (for sanity reasons).

**Comment by IanJermyn** [comment] 2016-03-04 12:58
Thank you for your replies.

Loading default settings does not change anything, partly because I never
changed them.

The problem shows up in the 'Hello' document, where the inline Gamma
function equation does not render. Another, more trivial example:

This does not render: $\phi$, whereas this does: $$\phi$$.

As I say, this all works under classeur, in the same browser at the same
time, in neighbouring tabs. Any theories as to why they might be different?

Thanks for your help.

Ian.

**Comment by benweet** [comment] 2016-03-04 13:03
I can't reproduce that. What are the browser and OS versions?
If chrome, can you try with your extensions disabled temporarily?

**Comment by IanJermyn** [comment] 2016-03-04 14:12
Chrome, Windows 10.

In incognito mode, it works. I am currently trying to find out which
extension is clashing with StackEdit, and I will post the results here.
However, as I say, classeur works fine with all extensions enabled, and I
would greatly prefer this to be the case for StackEdit too.

Ian.

**Comment by IanJermyn** [comment] 2016-03-04 16:38
It is an extension called MathJax for Chrome (
https://chrome.google.com/webstore/detail/mathjax-for-chrome/elbbpgnifnallkilnkofjcgjeallfcfa?utm_source=chrome-app-launcher-info-dialog)
that is causing the problem. Disabling it solves the problem. This is not
ideal, as, although this extension is a bit crap, as I understood it, it is
the only way that Chrome renders MathML. Having said that,
math.stackexchange works fine, so it is plain I do not know what is going
on!

**Comment by IanJermyn** [comment] 2016-03-04 16:40
And this still does not explain why classeur works even with the extension
enabled.

**Comment by benweet** [comment] 2016-03-04 16:42
Classeur is not based on StackEdit. It's another project built from scratch.

**Comment by IanJermyn** [comment] 2016-03-04 17:45
Maybe so, but it also renders MathML, and without clashing with the
extension.

**Comment by benweet** [comment] 2017-11-22 23:09
Please open a new ticket if not fixed in the v5.

**Closed by benweet** 2017-11-22 23:09 UTC
