### ISSUE TITLE
Unable to control the size of images

### ISSUE THREAD

**Issue by AshwinJay** [benweet/stackedit#164] opened 2013-11-05 03:27 UTC
How do I add a size hint to images?

Thanks. Great tool!

**Comment by mickeypash** [comment] 2015-01-25 16:56
+1

**Comment by veegee** [comment] 2015-02-04 23:09
+1

**Comment by aaronchi** [comment] 2015-02-08 15:18
+1

**Comment by rfpuyana** [comment] 2015-03-10 22:30
+1

**Comment by CarlesCG** [comment] 2015-03-26 12:20
+1

**Comment by farzher** [comment] 2015-04-10 01:28
+1 :+1:

**Comment by monolithed** [comment] 2015-05-05 00:17
+1

**Comment by davidbenque** [comment] 2015-05-15 16:09
+1

**Comment by nirgn975** [comment] 2015-06-05 14:08
+1

**Comment by kjones13** [comment] 2015-06-10 15:25
+1

**Comment by 0000marcell** [comment] 2015-08-10 23:16
+1

**Comment by diegofaria** [comment] 2015-08-28 14:25
+1

**Comment by holtgrewe** [comment] 2015-09-01 16:45
+1

**Comment by sterpe** [comment] 2015-09-06 21:42
+1

**Comment by dfiru** [comment] 2015-09-08 22:45
+1

**Comment by danrpts** [comment] 2015-10-05 07:17
+1

**Comment by vladejs** [comment] 2015-10-08 16:57
Can you add a custom extension that intercepts the image conversion and accept a new sintax?

Like ![desc](url){attributes}

**Comment by ajorquera** [comment] 2015-10-15 16:05
+1

**Comment by ChristianRich** [comment] 2015-10-26 22:53
+1

**Comment by estebancastro** [comment] 2015-10-29 22:56
+1

**Comment by eddieberklee** [comment] 2015-11-03 08:54
+1

**Comment by cmoulliard** [comment] 2015-11-05 09:36
+1

**Comment by nikolaikopernik** [comment] 2015-11-20 11:38
+1

**Comment by wpinaud** [comment] 2015-11-24 13:21
+1

**Comment by prankymat** [comment] 2015-12-17 09:56
pleeeease +1

**Comment by ctesta01** [comment] 2015-12-17 21:38
ugh yes +1

**Comment by oldergod** [comment] 2015-12-31 08:38
+1

**Comment by oMMuCo** [comment] 2016-01-18 23:35
+1

**Comment by sbanerjee23** [comment] 2016-01-21 02:25
+1

**Comment by FinnVonFriesland** [comment] 2016-01-22 16:34
+1

**Comment by eddieberklee** [comment] 2016-01-22 20:34
Everyone who +1'd is getting hit back with karma, as the notifications for
others below you +1ing piles up in your inbox.

**Comment by francescobragagna** [comment] 2016-02-24 10:03
+1

**Comment by eraly** [comment] 2016-02-24 17:04
+1

**Comment by eddieberklee** [comment] 2016-07-27 06:31
Hi benweet/stackedit,

I'd like to add you to my professional network on LinkedIn.

- Edward

Confirm that you know Edward: https://www.linkedin.com/e/v2?e=0-ir4ijeuo-dd&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=ATIkXsnQ&invitationId=6163953587983568896








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ir4ijeuo-dd&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQE2Pjn6ap41BQAAAVYrDPSZHZA0FHhkJfUf8L7NW9Nma_tb7RNmspsLw9j24hV8YQV4PYY604OB8xim8pv8Kg2vNMYUSVXoXDw4_bRK4afnyNFwMhBzM7QzT6uvGHZDk_mr8VzYmzmbb6LAkV0RMKXVMr01tPwpmH7JFfOyzHTmbqpEkQsmfW_HXAxjYCXCEHb_&eid=0-ir4ijeuo-dd


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ir4ijeuo-dd&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by nesteruk** [comment] 2016-09-29 22:40
+1

**Comment by romanrandom** [comment] 2016-09-30 14:33
+1

**Comment by vpong** [comment] 2016-11-25 19:04
+1

**Comment by roman-ku** [comment] 2016-12-28 00:37
+1

**Comment by Muxelmann** [comment] 2017-01-23 16:43
+1

**Comment by anettegj** [comment] 2017-02-06 12:53
+1

**Comment by mghassany** [comment] 2017-02-21 15:08
+1

**Comment by killkrt** [comment] 2017-03-12 20:44
+1

**Comment by championofblocks** [comment] 2017-06-16 09:07
+1

**Comment by Ralphilius** [comment] 2017-06-25 11:51
+1
Almost 4 years and it's not implemented yet

**Comment by Pabloin** [comment] 2017-09-05 00:59
+1

**Comment by balmandhunter** [comment] 2017-10-03 16:46
+1

**Comment by ravi9884** [comment] 2017-10-23 01:56
+1

**Comment by amerocu** [comment] 2018-01-04 15:09
+1

**Comment by hammonja** [comment] 2018-02-04 08:32
+1

**Comment by vonzcy** [comment] 2018-03-16 04:27
+1

**Comment by vonzcy** [comment] 2018-03-16 04:29
Actually the `<img src="http://....jpg" width="200px" height="200px" />` works well enough, though having `![](url =widthxheight)` support would be cool.

**Comment by vonzcy** [comment] 2018-03-16 04:35
But the problem is, seems the adjustment with embedded CSS is to scale the image that has already been scaled once. That means, if you enlarge the image again, it would be blurred.

**Comment by benweet** [comment] 2018-04-08 17:07
Fixed in v5.11. Syntax is `![test](image.png =100x200)`.

**Closed by benweet** 2018-04-08 17:07 UTC
Labels: enhancement, question

**Comment by sufiankaki** [comment] 2020-10-01 05:10
> Fixed in v5.11. Syntax is `![test](image.png =100x200)`.

Wonderful! But when the document is exported, the image isn't available in PDF. Neither does using an <img> tag images. Any solution to this please?
