### ISSUE TITLE
V5/It is supposed to sync but it is not

### ISSUE THREAD

**Issue by ferdossi** [benweet/stackedit#1128] opened 2017-10-06 14:35 UTC
Hi, 

This tool is supposed to sync with the cloud the same file between different browsers but it is not:

1-Open a file on your google account  =>OK

2-Start editing it and sync it   =>OK, let's say it is the V1 on your file

3-Open the same file on another device and do some changes and sync =>OK, the V2 of your file is in the cloud

4-Go back to the first device where the file is already opened as V1 (at this point what should be done to see the changes done on the second device ?)

5-Without any edition, perfom a sync action just to fetch lastest changes done on the V2 => NOT OK, by doing that, your local file (V1) will simply overwrite the cloud file (V2) without detecting all changes done on the second device

So how can it be called a synchronization, it is just a unilateral save action in the cloud.
Am I missing something?

Cheers

**Comment by benweet** [comment] 2017-10-06 14:49
Yes, you are.

When you hit the "synchronize now" button (which is automatically done every minute by the way), it downloads file changes from Google, performs merge with your local changes, and uploads the merged file back to Google. So both editors should have the same merged content at some point.

**Comment by ferdossi** [comment] 2017-10-06 15:12
I am sorry but that is not true, I did it several times on many devices/browsers and it always ends up the same way, changes are not detected on the first devices and the last version of my file on google is replaced with the previous one, there is no merge

**Comment by ferdossi** [comment] 2017-10-06 15:46
can you take some time looking at this video and tell what am I doing wrong please

[https://youtu.be/CG7mcveigws](https://youtu.be/CG7mcveigws
)

**Comment by benweet** [comment] 2017-10-06 16:00
Right, it's probably a bug. I'll have a look a this ASAP.

**Comment by benweet** [comment] 2017-10-06 17:53
Reproduced! Will deploy a fix in the next couple of days.

**Comment by ferdossi** [comment] 2017-10-06 19:36
Nice, many thanks

**Comment by ferdossi** [comment] 2017-10-16 08:12
I saw that you made a fix and indeed there is a sync done when opening a file on a different device, most of the time it works fine but honestly this sync is not completely reliable.

It happened to me many times these last days when switching from one device to another, the sync on a second device that still contains the n-1 version is not accurate at all and many lines disappear after a sort of merge.

Could it be that it is related to the auto upgrade process of stackedit?

**Comment by benweet** [comment] 2017-11-05 12:14
I can't reproduce this. Please open a new ticket with more information about how to reproduce the problem.

**Closed by benweet** 2017-11-05 12:14 UTC
Labels: bug

**Comment by snospmiS** [comment] 2018-03-17 17:08
Hi there!

Is the process of merging local and cloud data together intended? 
Because, as I use StackEdit on different devices, this produces some unpleasant side effects. 

Let me give an example:

**Step 1**: Using my PC, signed in via Google, I create a new file named "_Test_" and write "_123_".
**Step 2**: StackEdit automatically synchronizes and the data is stored locally and in GoogleDrive.
**Step 3**: I open StackEdit on my tablet (signed in) and it syncs with GoogleDrive so I get my "_Test_" file which contains "_123_". Now I delete this text and instead write "_456_". After the auto-sync, I close StackEdit.
**Step 4**: Back on my PC, I open StackEdit again, and the old local "_Test_" file which still contains "_123_" is merged with the newer cloud file which contains "_456_". What I get is a new file which contains "_456123_".

As already stated, this is kind of unpleasant when editing files on different devices.

Nevertheless, I LOVE StackEdit!

Best wishes!
