### ISSUE TITLE
Pressing Backspace deletes the file when editing the file name

### ISSUE THREAD

**Issue by JINKEHE** [benweet/stackedit#1270] opened 2018-03-16 13:01 UTC
Is there any way to make the key backspace do not delete file? Cheers.

**Comment by 27359794** [comment] 2018-03-18 14:15
+1, this is a really serious problem. Steps to reproduce.

1. Create a new file (or edit existing filename)
2. Type some stuff in the filename box
3. Hit backspace a bunch of times in quick succession, with the expectation of deleting what you've written

This will result in the accidental deletion of several files at the same time, with no indication of what's happening. At first, I didn't even realise what happened, and thought there'd been some sync corruption issue and my files were permanently lost. Luckily I checked the Trash folder.

Since file deletion is a big deal, I recommend disabling deletion-by-backspace.

**Comment by benweet** [comment] 2018-03-18 19:00
Should be fixed in v5.10.1.

**Closed by benweet** 2018-03-18 19:00 UTC
Labels: bug
