### ISSUE TITLE
feature request: plain text highlight function 

### ISSUE THREAD

**Issue by leewi9** [benweet/stackedit#1034] opened 2016-11-04 05:11 UTC
use certain symbol such as `==` to highlight plain text, like below

markdown:
```
==highlighted plain text==
```

preview:
![image](https://cloud.githubusercontent.com/assets/10832544/19995213/27f94ed4-a290-11e6-860b-263c5688f2a2.png)

**Comment by benweet** [comment] 2017-10-04 15:59
Duplicate of #1121.

**Closed by benweet** 2017-10-04 15:59 UTC
