### ISSUE TITLE
Pdf Unauthorized

### ISSUE THREAD

**Issue by nicolascrop** [benweet/stackedit#930] opened 2016-01-04 08:28 UTC
Hi, 
Happy new year and i must say, i love stackedit, it's a really good app.
However since last week (I started to use it again after a few months) I juste can't generate PDF anymore. It says: Unauthorized in the bottom right corner.
What i have to do to make it work again?

**Comment by webmink** [comment] 2016-01-05 13:14
I'm a subscriber and I am also getting this issue. When I select Export to disk, I see "As PDF" followed by "sponsor" in red. When I select it, in the majority of cases I get:
>  Error when trying to generate PDF: Unauthorized
It has worked a couple of times but there's no rationale for why. I don't see any reference to Sponsoring anywhere else and Monetizer.js shows me as a subscriber.

**Comment by RoyiAvital** [comment] 2016-01-06 17:58
Same issue here...

**Comment by benweet** [comment] 2016-01-06 18:44
Works fine for me. Can you guys provide your MonetizeJS user IDs?

**Comment by webmink** [comment] 2016-01-06 18:50
Mine is simon@webmionk.com

**Comment by benweet** [comment] 2016-01-06 18:52
@webmink you can find your user ID here:
https://monetizejs.com/account

**Comment by webmink** [comment] 2016-01-06 18:58
That would be lz4y97FhhzQduAru then :-)

**Comment by benweet** [comment] 2016-01-06 19:26
I can't reproduce the problem. Probably a temporary issue on MonetizeJS side. Do you still have it at the moment?

**Comment by webmink** [comment] 2016-01-06 19:28
Yes, still happening every time I'm afraid. Want to watch on a Hangout?


On Wed, Jan 6, 2016 at 7:26 PM, Benoit Schweblin <notifications@github.com>
wrote:

> I can't reproduce the problem. Probably a temporary issue on MonetizeJS
> side. Do you still have it at the moment?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benweet/stackedit/issues/930#issuecomment-169429395>.
>



-- 
*Simon Phipps*  http://webmink.com

*Office:* +1 (415) 683-7660 *or* +44 (238) 098 7027
*Signal/Mobile*:  +44 774 776 2816
*or Telegram <https://telegram.me/webmink> *

**Comment by benweet** [comment] 2016-01-06 19:59
@webmink sure. You can send me an invite at benoit@classeur.com.

**Comment by RoyiAvital** [comment] 2016-01-06 22:12
My ID is:

mKsutbv1WQDMQUec

I still have the problem each and every time (Missed a dead line at university because of that).

I will send you and invitation to your G+ account.

**Comment by benweet** [comment] 2016-01-06 22:22
@RoyiAvital do you have the exact same error? ("PDF: Unauthorized")

Did you try with only a few letters to check that it's not related to the content of the document?

**Comment by nicolascrop** [comment] 2016-01-06 22:27
I might have found the ssource of the problem. Even on a very small document it does not work
when you use the " > " command
this: " > kllsk" is the whole content of my Document and it throw the error mentioned above

**Comment by benweet** [comment] 2016-01-06 22:32
Reproduced!
Investigating...

**Comment by RoyiAvital** [comment] 2016-01-06 23:11
@benweet 
I'm not on the computer now, I will try tomorrow and report.
I tend to say yes, yet I want to verify.

For sure I didn't use ">" I only use math equations and regular text.

**Comment by benweet** [comment] 2016-01-07 00:11
Should be fixed now. Let me know if you still have it.

**Closed by benweet** 2016-01-07 00:11 UTC

**Comment by webmink** [comment] 2016-01-07 10:39
Good news:  A document is now generated every time.
Bad news: The resulting document is empty apart from this message:

This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

On Thu, Jan 7, 2016 at 12:11 AM, Benoit Schweblin <notifications@github.com>
wrote:

> Should be fixed now. Let me know if you still have it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benweet/stackedit/issues/930#issuecomment-169505153>.
>



-- 
*Simon Phipps*  http://webmink.com

*Office:* +1 (415) 683-7660 *or* +44 (238) 098 7027
*Signal/Mobile*:  +44 774 776 2816
*or Telegram <https://telegram.me/webmink> *

**Comment by nicolascrop** [comment] 2016-01-07 10:43
It works for me, even on a complex document
